from random import randint

# commented out are too vague; hardmode by uncommenting lol
diseases = [
    "COVID-19",
    "Alzheimer’s disease",
    "Diabetes I",
	"Diabetes II",
    "Influenza",
	"Pneumonia",
    "Kidney Cancer",
    "Liver Cancer",
    # "Hypertension",
    # "Obesity",
    # "Drug overdose",
    "Parkinson’s disease",
    "HIV/AIDS",
    # "Liver cirrhosis",
    # "Osteoarthritis",
    # "Rheumatoid arthritis",
    "Depression",
    # "Gastroesophageal reflux disease",
    "Asthma",
    # "COPD",
    "Epilepsy",
    "Breast cancer",
    # "Prostate cancer",
    # "Colon cancer",
    # "Pancreatic cancer",
    "Leukemia",
    "Lung cancer",
    "Skin cancer",
    # "Hepatitis",
    # "Glaucoma",
    # "Cataracts",
    "Dementia",
    # "Multiple sclerosis",
    # "Endometriosis",
    # "Sickle cell anemia",
    # "Celiac disease",
    # "Crohn’s disease",
    # "Ulcerative colitis",
    # "Lupus",
    # "Fibromyalgia",
    # "Sleep apnea",
    "Osteoporosis",
    "Hemorrhoids",
    # "Gout",
    # "Psoriasis",
    "Tuberculosis",
    # "Lyme disease",
    # "Chlamydia",
    # "Gonorrhea",
    "Syphilis",
    "Herpes",
    # "Human papillomavirus",
    "Measles",
    # "Mumps",
    # "Rubella",
    "Varicella (chickenpox)",
    "Zika virus",
    # "West Nile virus",
    "Ebola",
    "Malaria",
    "Yellow fever",
    "Cholera",
    # "Typhoid fever",
    # "Dengue fever",
    # "Lassa fever",
    # "Hantavirus",
    "Rabies",
    "Tetanus",
    # "Botulism",
    # "Anthrax",
    # "Black Plague",
    # "Smallpox",
    # "Polio",
    # "Norovirus",
    # "Salmonella",
    # "E. coli infection",
    # "Listeria",
    # "Campylobacter",
    # "Toxoplasmosis",
    # "Cryptosporidiosis",
    # "Giardiasis",
    # "Trichomoniasis",
    # "Scabies",
    "Head Lice",
    # "Ringworm infestation",
    # "Pinworm infection",
    "Bedbugs",
    # "MRSA (methicillin-resistant Staphylococcus aureus)",
    # "Clostridioides difficile infection",
    # "Legionnaires’ disease",
    "Tuberculosis",
	"Hepatitis",
    "Syphilis",
    # "Gonorrhea",
    "Chlamydia"
    # "Human papillomavirus (HPV)",
    # "Herpes simplex virus (HSV)",
    # "Trichomoniasis",
    # "Pelvic inflammatory disease (PID)",
    # "Genital warts",
    # "Genital herpes",
    # "Chancroid",
    # "Lymphogranuloma venereum (LGV)",
    # "Granuloma inguinale",
    # "Molluscum contagiosum",
]

def getDisease():
	return diseases[randint(0, len(diseases) - 1)]